import Head from 'next/head'
import React from 'react';

import {CartPage} from '../../components/templates/CartPage/index';
import {MainLayout} from '../../components/layout/MainLayout';
import {Breadcrumbs} from '../../components/modules/Breadcrumbs/Breadcrumbs';
import {AboutPage} from '../../components/templates/About/index';

export default function About() {

  const getDefaultTextGenerator = React.useCallback(() => 'О нас', [])
  const getTextGenerator = React.useCallback((param: string) => ({}[param]), []);

  return (
    <>
      <Head>
        <title>Loft Мебель</title>
        <meta charSet='UTF-8'/>
        <meta httpEquiv='X-UA-Compatible' content='IE-edge'/>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel={'icon'} type={'image/svg'} size={'32x32'} href={'/img/LogoSmall.svg'}/>
      </Head>
      <MainLayout>
        <main>
          <Breadcrumbs
            getDefaultTextGenerator={getDefaultTextGenerator}
            getTextGenerator={getTextGenerator}
          />
          <AboutPage/>
        </main>
      </MainLayout>
    </>
  )
}


