import Head from 'next/head'
import {Header} from '../components/modules/Header/Header';
import {Footer} from '../components/modules/Footer/Footer';
import {MainPage} from '../components/templates/MainPage/index';
import {useAppDispatch} from '../hooks/redux';
import {fetchSofas} from '../store/reducers/ActionCreators';
import React from 'react';
import { useGetSofasBestsellersQuery } from '@/store/sofa/sofa.api';

export default function Home() {

  const dispatch = useAppDispatch()

  //TODO Сделать Лэйаут

/*  const {data, error, isLoading} = useGetSofasQuery()*/



 /* React.useEffect(() => {
    fetchSofas(dispatch)
  }, [])*/

  return (
    <>
      <Head>
        <title>Loft Мебель</title>
        <meta charSet='UTF-8'/>
        <meta httpEquiv='X-UA-Compatible' content='IE-edge'/>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel={'icon'} type={'image/svg'} size={'32x32'} href={'/img/LogoSmall.svg'}/>

      </Head>
      <Header/>
      <MainPage/>
      <Footer/>
    </>
)
}
